import { cards } from './cards'
import { hero } from './hero'
import { productsNavigation } from './productsNavigation'
import { infoSection } from './infoSection'
import { multiInfoSection } from './multiInfoSection'
import { stats } from './stats'
import { soloCta } from './soloCta'
import { accordions } from './accordions'
import { content } from './content'
import { splitContent } from './splitContent'
import { imageBanner } from './imageBanner'
export { hero, cards, productsNavigation, infoSection, multiInfoSection, stats, soloCta, accordions, content, splitContent, imageBanner }
